const ROOT_README_PATH = "README.md";
const PROFILE_START_MARKER = "<!-- LEETBRIDGE_PROFILE_START -->";
const PROFILE_END_MARKER = "<!-- LEETBRIDGE_PROFILE_END -->";
const SOLUTIONS_START_MARKER = "<!-- SOLUTIONS_START -->";
const SOLUTIONS_END_MARKER = "<!-- SOLUTIONS_END -->";

function normalizeInlineText(value, fallback) {
    const normalized = String(value ?? "")
        .replace(/[\r\n]+/g, " ")
        .replace(/\s+/g, " ")
        .trim();

    return normalized || fallback;
}

function escapeMarkdownTableText(value) {
    return normalizeInlineText(value, "Unknown")
        .replace(/\\/g, "\\\\")
        .replace(/\|/g, "\\|");
}

function unescapeMarkdownTableText(value) {
    return value.replace(/\\\|/g, "|").replace(/\\\\/g, "\\");
}

function normalizeDifficulty(value) {
    const normalized = normalizeInlineText(value, "Unknown");

    return ["Easy", "Medium", "Hard"].find((difficulty) => (
        normalized.includes(difficulty)
    )) ?? normalized;
}

function getDifficultyIcon(difficulty) {
    return {
        Easy: "🟢",
        Medium: "🟡",
        Hard: "🔴"
    }[difficulty] ?? "⚪";
}

function escapeHtmlAttribute(value) {
    return String(value)
        .replace(/&/g, "&amp;")
        .replace(/"/g, "&quot;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
}

function escapeMermaidLabel(value) {
    return normalizeInlineText(value, "Unknown").replace(/"/g, "'");
}

function buildProblemReadme(problem, solutions) {
    const title = normalizeInlineText(problem.title, problem.slug);
    const numberPrefix = problem.number ? `${problem.number}. ` : "";
    const difficulty = normalizeInlineText(problem.difficulty, "Unknown");
    const solutionRows = solutions.map((solution) => {
        const fileName = solution.path.split("/").pop();

        return `| ${escapeMarkdownTableText(solution.language)} `
            + `| [${fileName}](${fileName}) |`;
    });

    return [
        "<!-- This file is automatically generated by LeetBridge. -->",
        "",
        `# ${numberPrefix}${title}`,
        "",
        `**Difficulty:** ${difficulty}`,
        "",
        `[View the problem on LeetCode](https://leetcode.com/problems/${problem.slug}/)`,
        "",
        "## Solutions",
        "",
        "| Language | File |",
        "| --- | --- |",
        ...solutionRows,
        ""
    ].join("\n");
}

function titleFromProblemSlug(slug) {
    return String(slug ?? "")
        .split("-")
        .filter(Boolean)
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(" ");
}

function parseProblemReadmeMetadata(readme, fallback) {
    const headingMatch = readme.match(/^#\s+(?:(\d+)\.\s+)?(.+)$/m);
    const difficultyMatch = readme.match(/^\*\*Difficulty:\*\*\s+(.+)$/m);

    return {
        number: headingMatch?.[1]
            ? Number(headingMatch[1])
            : fallback.number,
        slug: fallback.slug,
        title: normalizeInlineText(
            headingMatch?.[2],
            titleFromProblemSlug(fallback.slug)
        ),
        difficulty: normalizeInlineText(
            difficultyMatch?.[1],
            "Unknown"
        )
    };
}

function splitMarkdownTableRow(line) {
    const placeholder = "\u0000";

    return line
        .slice(1, -1)
        .replace(/\\\|/g, placeholder)
        .split("|")
        .map((cell) => (
            cell.trim().replaceAll(placeholder, "\\|")
        ));
}

function parseRootReadmeEntries(readme) {
    const startIndex = readme.indexOf(SOLUTIONS_START_MARKER);
    const endIndex = readme.indexOf(SOLUTIONS_END_MARKER);

    if (startIndex === -1 || endIndex <= startIndex) {
        return [];
    }

    const generatedSection = readme.slice(startIndex, endIndex);
    const entries = [];

    for (const line of generatedSection.split(/\r?\n/)) {
        if (!line.startsWith("| [") || !line.endsWith("|")) {
            continue;
        }

        const cells = splitMarkdownTableRow(line);

        if (cells.length !== 4) {
            continue;
        }

        const problemMatch = cells[0].match(
            /^\[(\d+)\]\(https:\/\/leetcode\.com\/problems\/([a-z0-9-]+)\/\)$/
        );

        if (!problemMatch) {
            continue;
        }

        const solutions = [];
        const solutionPattern = /\[([^\]]+)\]\(([^)]+)\)/g;
        let solutionMatch = solutionPattern.exec(cells[3]);

        while (solutionMatch) {
            solutions.push({
                language: unescapeMarkdownTableText(solutionMatch[1]),
                path: solutionMatch[2]
            });
            solutionMatch = solutionPattern.exec(cells[3]);
        }

        entries.push({
            number: Number(problemMatch[1]),
            slug: problemMatch[2],
            title: unescapeMarkdownTableText(cells[1]),
            difficulty: normalizeDifficulty(cells[2]),
            solutions
        });
    }

    return entries;
}

function mergeProblemEntry(entries, problem, solutions) {
    const nextEntry = {
        number: problem.number ?? null,
        slug: problem.slug,
        title: normalizeInlineText(problem.title, problem.slug),
        difficulty: normalizeDifficulty(problem.difficulty),
        solutions
    };
    const filteredEntries = entries.filter((entry) => (
        entry.slug !== nextEntry.slug
        && (
            !nextEntry.number
            || entry.number !== nextEntry.number
        )
    ));

    return [...filteredEntries, nextEntry].sort((first, second) => {
        if (first.number && second.number) {
            return first.number - second.number;
        }

        if (first.number) {
            return -1;
        }

        if (second.number) {
            return 1;
        }

        return first.slug.localeCompare(second.slug);
    });
}

function buildRootReadmeSection(entries) {
    const difficultyCounts = entries.reduce((counts, entry) => {
        if (Object.hasOwn(counts, entry.difficulty)) {
            counts[entry.difficulty] += 1;
        }

        return counts;
    }, { Easy: 0, Medium: 0, Hard: 0 });
    const languageCounts = entries.reduce((counts, entry) => {
        for (const solution of entry.solutions) {
            const language = normalizeInlineText(solution.language, "Unknown");
            counts.set(language, (counts.get(language) ?? 0) + 1);
        }

        return counts;
    }, new Map());
    const difficultyChart = Object.entries(difficultyCounts)
        .filter(([, count]) => count > 0)
        .map(([difficulty, count]) => (
            `    "${escapeMermaidLabel(difficulty)}" : ${count}`
        ));
    const languageRows = [...languageCounts.entries()]
        .sort((first, second) => (
            second[1] - first[1] || first[0].localeCompare(second[0])
        ))
        .map(([language, count]) => (
            `| ${escapeMarkdownTableText(language)} | ${count} |`
        ));
    const solutionRows = entries.map((entry) => {
        const number = entry.number
            ? String(entry.number).padStart(4, "0")
            : "N/A";
        const solutions = entry.solutions.map((solution) => (
            `[${escapeMarkdownTableText(solution.language)}](${solution.path})`
        )).join("<br>");

        return `| [${number}](https://leetcode.com/problems/${entry.slug}/) `
            + `| ${escapeMarkdownTableText(entry.title)} `
            + `| ${getDifficultyIcon(entry.difficulty)} `
            + `${escapeMarkdownTableText(entry.difficulty)} `
            + `| ${solutions || "None"} |`;
    });
    const problemLabel = entries.length === 1 ? "problem" : "problems";

    return [
        SOLUTIONS_START_MARKER,
        "",
        "## Progress",
        "",
        `**${entries.length} ${problemLabel} solved**`,
        "",
        "| Total | 🟢 Easy | 🟡 Medium | 🔴 Hard |",
        "| ---: | ---: | ---: | ---: |",
        `| ${entries.length} | ${difficultyCounts.Easy} `
            + `| ${difficultyCounts.Medium} | ${difficultyCounts.Hard} |`,
        "",
        ...(difficultyChart.length > 0 ? [
            "### Difficulty breakdown",
            "",
            "```mermaid",
            "pie showData",
            "    title Solved problems by difficulty",
            ...difficultyChart,
            "```",
            ""
        ] : []),
        ...(languageRows.length > 0 ? [
            "### Languages",
            "",
            "| Language | Solutions |",
            "| --- | ---: |",
            ...languageRows,
            ""
        ] : []),
        "## Solutions",
        "",
        "| # | Title | Difficulty | Solution |",
        "| ---: | --- | --- | --- |",
        ...solutionRows,
        "",
        SOLUTIONS_END_MARKER
    ].join("\n");
}

function buildRepositoryProfileSection(leetcodeUsername) {
    if (!leetcodeUsername) {
        return "";
    }

    const username = encodeURIComponent(leetcodeUsername);
    const safeUsername = escapeHtmlAttribute(leetcodeUsername);
    const profileUrl = `https://leetcode.com/u/${username}/`;
    const statsUrl = `https://leetcard.jacoblin.cool/${username}`
        + "?theme=transparent&font=Inter";
    const heatmapUrl = `https://leetcard.jacoblin.cool/${username}`
        + "?ext=heatmap&theme=transparent";

    return [
        PROFILE_START_MARKER,
        "",
        "## LeetCode Profile",
        "",
        "<p align=\"center\">",
        `  <a href=\"${profileUrl}\">`,
        `    <img src=\"${statsUrl}\" alt=\"LeetCode stats for ${safeUsername}\" width=\"49%\">`,
        "  </a>",
        `  <a href=\"${profileUrl}\">`,
        `    <img src=\"${heatmapUrl}\" alt=\"LeetCode activity for ${safeUsername}\" width=\"49%\">`,
        "  </a>",
        "</p>",
        "",
        PROFILE_END_MARKER
    ].join("\n");
}

function buildLegacyRepositoryProfileSection(leetcodeUsername) {
    const username = encodeURIComponent(leetcodeUsername);
    const profileUrl = `https://leetcode.com/u/${username}/`;

    return [
        "## LeetCode Profile",
        "",
        `[![LeetCode Stats](https://leetcard.jacoblin.cool/${username}?theme=light&font=Inter)](${profileUrl})`,
        "",
        `[![LeetCode Activity](https://leetcard.jacoblin.cool/${username}?ext=heatmap&theme=light)](${profileUrl})`
    ].join("\n");
}

function updateRepositoryProfileSection(existingReadme, leetcodeUsername) {
    if (!leetcodeUsername) {
        return existingReadme;
    }

    const generatedSection = buildRepositoryProfileSection(leetcodeUsername);
    const startIndex = existingReadme.indexOf(PROFILE_START_MARKER);
    const endIndex = existingReadme.indexOf(PROFILE_END_MARKER);

    if ((startIndex === -1) !== (endIndex === -1) || endIndex < startIndex) {
        throw new Error(
            "The repository README has invalid LeetBridge profile markers"
        );
    }

    if (startIndex !== -1) {
        const suffixIndex = endIndex + PROFILE_END_MARKER.length;

        return existingReadme.slice(0, startIndex)
            + generatedSection
            + existingReadme.slice(suffixIndex);
    }

    const legacySection = buildLegacyRepositoryProfileSection(
        leetcodeUsername
    );

    return existingReadme.includes(legacySection)
        ? existingReadme.replace(legacySection, generatedSection)
        : existingReadme;
}

function buildRepositoryReadmeIntroduction(leetcodeUsername) {
    const lines = [
        "# LeetCode Solutions",
        "",
        "A collection of accepted LeetCode solutions automatically synced by LeetBridge."
    ];

    if (leetcodeUsername) {
        lines.push(
            "",
            buildRepositoryProfileSection(leetcodeUsername)
        );
    }

    return lines.join("\n");
}

function updateRootReadme(
    existingReadme,
    generatedSection,
    leetcodeUsername = null
) {
    const readme = updateRepositoryProfileSection(
        existingReadme,
        leetcodeUsername
    );
    const startIndex = readme.indexOf(SOLUTIONS_START_MARKER);
    const endIndex = readme.indexOf(SOLUTIONS_END_MARKER);
    const hasDuplicateStart = startIndex !== -1
        && readme.indexOf(
            SOLUTIONS_START_MARKER,
            startIndex + SOLUTIONS_START_MARKER.length
        ) !== -1;
    const hasDuplicateEnd = endIndex !== -1
        && readme.indexOf(
            SOLUTIONS_END_MARKER,
            endIndex + SOLUTIONS_END_MARKER.length
        ) !== -1;

    if (
        (startIndex === -1) !== (endIndex === -1)
        || (startIndex !== -1 && endIndex <= startIndex)
        || hasDuplicateStart
        || hasDuplicateEnd
    ) {
        throw new Error(
            "The repository README has invalid LeetBridge solution markers"
        );
    }

    if (startIndex !== -1) {
        const suffixIndex = endIndex + SOLUTIONS_END_MARKER.length;

        return readme.slice(0, startIndex)
            + generatedSection
            + readme.slice(suffixIndex);
    }

    const existing = readme.trimEnd();
    const introduction = existing
        || buildRepositoryReadmeIntroduction(leetcodeUsername);

    return `${introduction}\n\n${generatedSection}\n`;
}
