const ROOT_README_PATH = "README.md";
const SOLUTIONS_START_MARKER = "<!-- SOLUTIONS_START -->";
const SOLUTIONS_END_MARKER = "<!-- SOLUTIONS_END -->";

function normalizeInlineText(value, fallback) {
    const normalized = String(value ?? "")
        .replace(/[\r\n]+/g, " ")
        .replace(/\s+/g, " ")
        .trim();

    return normalized || fallback;
}

function escapeMarkdownTableText(value) {
    return normalizeInlineText(value, "Unknown")
        .replace(/\\/g, "\\\\")
        .replace(/\|/g, "\\|");
}

function unescapeMarkdownTableText(value) {
    return value.replace(/\\\|/g, "|").replace(/\\\\/g, "\\");
}

function buildProblemReadme(problem, solutions) {
    const title = normalizeInlineText(problem.title, problem.slug);
    const numberPrefix = problem.number ? `${problem.number}. ` : "";
    const difficulty = normalizeInlineText(problem.difficulty, "Unknown");
    const solutionRows = solutions.map((solution) => {
        const fileName = solution.path.split("/").pop();

        return `| ${escapeMarkdownTableText(solution.language)} `
            + `| [${fileName}](${fileName}) |`;
    });

    return [
        "<!-- This file is automatically generated by LeetBridge. -->",
        "",
        `# ${numberPrefix}${title}`,
        "",
        `**Difficulty:** ${difficulty}`,
        "",
        `[View the problem on LeetCode](https://leetcode.com/problems/${problem.slug}/)`,
        "",
        "## Solutions",
        "",
        "| Language | File |",
        "| --- | --- |",
        ...solutionRows,
        ""
    ].join("\n");
}

function splitMarkdownTableRow(line) {
    const placeholder = "\u0000";

    return line
        .slice(1, -1)
        .replace(/\\\|/g, placeholder)
        .split("|")
        .map((cell) => (
            cell.trim().replaceAll(placeholder, "\\|")
        ));
}

function parseRootReadmeEntries(readme) {
    const startIndex = readme.indexOf(SOLUTIONS_START_MARKER);
    const endIndex = readme.indexOf(SOLUTIONS_END_MARKER);

    if (startIndex === -1 || endIndex <= startIndex) {
        return [];
    }

    const generatedSection = readme.slice(startIndex, endIndex);
    const entries = [];

    for (const line of generatedSection.split(/\r?\n/)) {
        if (!line.startsWith("| [") || !line.endsWith("|")) {
            continue;
        }

        const cells = splitMarkdownTableRow(line);

        if (cells.length !== 4) {
            continue;
        }

        const problemMatch = cells[0].match(
            /^\[(\d+)\]\(https:\/\/leetcode\.com\/problems\/([a-z0-9-]+)\/\)$/
        );

        if (!problemMatch) {
            continue;
        }

        const solutions = [];
        const solutionPattern = /\[([^\]]+)\]\(([^)]+)\)/g;
        let solutionMatch = solutionPattern.exec(cells[3]);

        while (solutionMatch) {
            solutions.push({
                language: unescapeMarkdownTableText(solutionMatch[1]),
                path: solutionMatch[2]
            });
            solutionMatch = solutionPattern.exec(cells[3]);
        }

        entries.push({
            number: Number(problemMatch[1]),
            slug: problemMatch[2],
            title: unescapeMarkdownTableText(cells[1]),
            difficulty: cells[2],
            solutions
        });
    }

    return entries;
}

function mergeProblemEntry(entries, problem, solutions) {
    const nextEntry = {
        number: problem.number ?? null,
        slug: problem.slug,
        title: normalizeInlineText(problem.title, problem.slug),
        difficulty: normalizeInlineText(problem.difficulty, "Unknown"),
        solutions
    };
    const filteredEntries = entries.filter((entry) => (
        entry.slug !== nextEntry.slug
        && (
            !nextEntry.number
            || entry.number !== nextEntry.number
        )
    ));

    return [...filteredEntries, nextEntry].sort((first, second) => {
        if (first.number && second.number) {
            return first.number - second.number;
        }

        if (first.number) {
            return -1;
        }

        if (second.number) {
            return 1;
        }

        return first.slug.localeCompare(second.slug);
    });
}

function buildRootReadmeSection(entries) {
    const difficultyCounts = entries.reduce((counts, entry) => {
        if (Object.hasOwn(counts, entry.difficulty)) {
            counts[entry.difficulty] += 1;
        }

        return counts;
    }, { Easy: 0, Medium: 0, Hard: 0 });
    const solutionRows = entries.map((entry) => {
        const number = entry.number
            ? String(entry.number).padStart(4, "0")
            : "N/A";
        const solutions = entry.solutions.map((solution) => (
            `[${escapeMarkdownTableText(solution.language)}](${solution.path})`
        )).join("<br>");

        return `| [${number}](https://leetcode.com/problems/${entry.slug}/) `
            + `| ${escapeMarkdownTableText(entry.title)} `
            + `| ${escapeMarkdownTableText(entry.difficulty)} `
            + `| ${solutions || "None"} |`;
    });
    const problemLabel = entries.length === 1 ? "problem" : "problems";

    return [
        SOLUTIONS_START_MARKER,
        "",
        "## Progress",
        "",
        `**${entries.length} ${problemLabel} solved**`,
        "",
        "| Total | Easy | Medium | Hard |",
        "| ---: | ---: | ---: | ---: |",
        `| ${entries.length} | ${difficultyCounts.Easy} `
            + `| ${difficultyCounts.Medium} | ${difficultyCounts.Hard} |`,
        "",
        "## Solutions",
        "",
        "| # | Title | Difficulty | Solution |",
        "| ---: | --- | --- | --- |",
        ...solutionRows,
        "",
        SOLUTIONS_END_MARKER
    ].join("\n");
}

function updateRootReadme(existingReadme, generatedSection) {
    const startIndex = existingReadme.indexOf(SOLUTIONS_START_MARKER);
    const endIndex = existingReadme.indexOf(SOLUTIONS_END_MARKER);
    const hasDuplicateStart = startIndex !== -1
        && existingReadme.indexOf(
            SOLUTIONS_START_MARKER,
            startIndex + SOLUTIONS_START_MARKER.length
        ) !== -1;
    const hasDuplicateEnd = endIndex !== -1
        && existingReadme.indexOf(
            SOLUTIONS_END_MARKER,
            endIndex + SOLUTIONS_END_MARKER.length
        ) !== -1;

    if (
        (startIndex === -1) !== (endIndex === -1)
        || (startIndex !== -1 && endIndex <= startIndex)
        || hasDuplicateStart
        || hasDuplicateEnd
    ) {
        throw new Error(
            "The repository README has invalid LeetBridge solution markers"
        );
    }

    if (startIndex !== -1) {
        const suffixIndex = endIndex + SOLUTIONS_END_MARKER.length;

        return existingReadme.slice(0, startIndex)
            + generatedSection
            + existingReadme.slice(suffixIndex);
    }

    const existing = existingReadme.trimEnd();
    const introduction = existing || [
        "# LeetCode Solutions",
        "",
        "Accepted solutions automatically synced by LeetBridge."
    ].join("\n");

    return `${introduction}\n\n${generatedSection}\n`;
}
